apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyujik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hyujik
  template:
    metadata:
      labels:
        app: hyujik
    spec:
      containers:
      - image: okteto.dev/hyujik:latest
        name: hyujik
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "1938d2cd-79dc-4053-941d-594cdf17cecf"
        - name: Vless_Path
          value: "/vl5gyh655"
        - name: Vmess_UUID
          value: "1938d2cd-79dc-4053-941d-594cdf17cecf"
        - name: Vmess_Path
          value: "/vm6gty67466"
        - name: Share_Path
          value: "/v2link"
